version: '3.8'

services:
  niyi5-landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: niyi5-landing-page 